### PR TITLE
Document CloudEvent conversions

### LINKED ISSUE #2: Add Legacy/CloudEvent Event Mapping
We should document the exact mapping for Legacy to CloudEvent payloads.

I suggest we use this repo to store mappings and add tooling to ensure the mapping in a specific framework is correct.

The first step would be to describe the mapping (ideally language-agnostically).

CC: @jskeet
See: go/bridging-event-types-in-the-functions-framework

### PR DESCRIPTION
**Pull request by jskeet**
This is incomplete, but I wanted to demonstrate some progress, and get early feedback on the general structure before going any further. (I won't have time to complete this until at least the end of the week anyway.)

When finished, this should fix #2.

### CODE REVIEW

**Comment by jskeet** [comment]
Okay - will come back to this to fill in the TBD sections when I get a chance.

**Comment by grant** [comment]
Hey @jskeet, we're getting closer to needing some public documentation on conversions. I think developers will really want to know the details to this conversion in the future.

I'm fine with TODOs. Do you want to get this PR in and we can keep refining it as time goes on?

**Comment by jskeet** [comment]
Will take it up again on Monday

**Comment by jskeet** [comment]
@grant: I've added a bit more information here for things I'm reasonably confident about in terms of Firestore/Firebase. I'm happy enough to merge now - PTAL and rebase/merge if you're happy as-is, or I can address comments and then merge tomorrow.

**Comment by juliehockett** [comment]
I also implemented https://github.com/GoogleCloudPlatform/functions-framework-go/pull/51 based on this, so it definitely works as intended :D

**Review by juliehockett — APPROVED** [review]

**Comment by jskeet** [comment]
Merging based on Julie's comment - it'll be as easy to create PRs to fix any problems as to comment on this one...

**Pull request merged**
